### ISSUE TITLE
Hoi4 Dlc installs not working

### ISSUE THREAD

**Issue by I58I** [pointfeev/CreamInstaller#113]
I don't know what to do anymore.
I have deactivated the firewall and tried it again. There are also two Hoi4 checkboxes with the same content.

**Comment by pointfeev** [comment]
About the HOI4 double checkboxes, could you take a picture so I can see what you mean exactly?

That alone is a sign that something is up with your game and maybe even steam installations. Can you right click both and see if they point to the same directories? If they have the same platform, same ID, and the same root directory, then I'll have to look into what went wrong with gathering as that shouldn't happen.

Regardless of the double issue, so long as one of them point to the right directory and have the right ID, there shouldn't be a problem and you're likely forgetting to download and install all DLC or update your currently manually installed DLC. Either that or you're forgetting to also check the Paradox Launcher box during selection.

**Comment by I58I** [comment]
![Screenshot 2023-05-28 181837](https://github.com/pointfeev/CreamInstaller/assets/134854629/f8a969d4-a0ee-464d-81bf-ad38fecdb58

When I opened their root directory they showed the same path.

**Comment by pointfeev** [comment]
Should be fixed in v4.9.1!

**Comment by I58I** [comment]
![Screenshot 2023-05-29 104002](https://github.com/pointfeev/CreamInstaller/assets/134854629/bf0f10f1-33e4-483d-8319-a896c2946621)
 
It still does not work, I still have HOI4 two times with the same directory and ID (I have uninstalled it  multiple times by now)

**Comment by pointfeev** [comment]
That config is correct, so if that's what you're basing the functionality of the program off of, then you need to take a better look at the bold note under usage instructions.
