### ISSUE TITLE
Scan bar gets stuck on appid 0

### ISSUE THREAD

**Issue by Luthier2** [pointfeev/CreamInstaller#58]
Nothing works and i cant figure out how to deal with it

**Comment by pointfeev** [comment]
Surely you can manage more information than that... like what games you chose to scan, what platforms they were on? I'm not a wizard.

**Comment by Luthier2** [comment]
Ok then, so i tried it out with xenoverse 2 on steam

**Comment by pointfeev** [comment]
This is likely fixed in v4.3.0.0, please let me know! :)

**Comment by Luthier2** [comment]
![image](https://user-images.githubusercontent.com/120297408/208790857-c16e9d80-2676-4663-853f-099004bf956f.png)
No it still doesn't work

**Comment by pointfeev** [comment]
Ah you meant a DLC appid, I thought you meant a game; should be fixed in v4.3.0.1

**Comment by Luthier2** [comment]
Thank you its fixed my problem
