### ISSUE TITLE
Unable to scan dlcs

### ISSUE THREAD

**Issue by Teng3Cheese** [pointfeev/CreamInstaller#59]
![image](https://user-images.githubusercontent.com/86346978/206892655-84623b53-2bce-42c4-ba14-040de4361e24.png)
the installer gets stuck on this screen while trying to scan my hoi4 Dlcs. I followed instructions and aquired the dlcs from elsewhere first and am trying to patch it.
it has been stuck on the window for the past 30 minutes or so
windows defender real time protection is off

**Comment by pointfeev** [comment]
Based on the weirdness of your UI, I'd try what I mentioned [here](https://github.com/pointfeev/CreamInstaller/issues/45#issuecomment-1267717775). Otherwise, it's going to be some sort of internet-related issue. Have you tried cancelling and retrying, are you not on a VPN or have you tried one, are you able to connect to the Steam store, have you scanned 200+ games and DLC within the past 10 minutes to potentially cause Steam to rate limit you? Those are the only things I can think of off the top of my head.

**Comment by pointfeev** [comment]
This is likely fixed in v4.3.0.0, please let me know! :)

**Comment by Teng3Cheese** [comment]
The problems still persist, i have acquired a vpn and reinstalled the game & their dlc several times. i have installed .NET Desktop Runtime 6.0. the weirdness of my ui might come in due to me using windows 11

do you have any idea or anything i can give you to pin point the problem

**Comment by pointfeev** [comment]
Well since I posted that 2-3 weeks ago, the program upgraded to .NET 7, so I'd try installing [.NET 7 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-7.0.1-windows-x64-installer) as well. If this issue isn't resolved in v4.3.0.1 then you can try running [this debug version](https://www.dropbox.com/s/ibk32beca67wvbt/CreamInstaller-debug.exe?dl=0) and telling me what the debug window outputs when this issue is occurring.

**Comment by Teng3Cheese** [comment]
![image](https://user-images.githubusercontent.com/86346978/210021560-d46a7973-ad6c-444a-8718-7fa9ffd4bde4.png)
is this what you want? i also installed.net 7 runtime

**Comment by Limyx826** [comment]
![image](https://user-images.githubusercontent.com/38696851/211526445-f12537e6-442c-4979-9b79-0bab1190f736.png)
Stuck at Hoi4 as well.

**Comment by Limyx826** [comment]
![image](https://user-images.githubusercontent.com/38696851/211527211-c0931d8d-7322-4944-9b3f-fb4b405b7a2d.png)
Mine is on Windows 10 btw

**Comment by pointfeev** [comment]
Should be fixed in v4.6.0.0!
